---
title: 변수와 할당
teaching: 10
exercises: 10
---

::::::::::::::::::::::::::::::::::::::: objectives

- 스칼라 값을 변수에 할당하고 해당 값으로 계산을 수행하는 프로그램을 작성합니다.
- 스칼라 할당을 사용하는 프로그램에서 값의 변화를 올바르게 추적합니다.

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: questions

- 프로그램에 데이터를 어떻게 저장할 수 있나요?

::::::::::::::::::::::::::::::::::::::::::::::::::

## 변수를 사용하여 값을 저장하세요.

- **변수(Variables)** 는 값들의 이름입니다.

- 변수명
  
  - 문자, 숫자, 밑줄 `_`(일반적으로 긴 변수명에서 단어를 분리하는 데 사용됨)**만** 포함할 수 있습니다.
  - 숫자로 시작할 수 없습니다.
  - **대소문자를 구분**합니다(age, Age, AGE는 서로 다른 세 개의 변수입니다).

- 변수의 이름은 여러분이나 다른 프로그래머가 그것이 무엇인지 알 수 있도록 의미가 있어야 합니다.

- `__alistairs_real_age` 와 같이 밑줄로 시작하는 변수명은 특별한 의미가 있으므로 그 규칙을 이해할 때까지는 그렇게 하지 않을 것입니다.

- 파이썬에서 `=` 기호는 오른쪽에 있는 값을 왼쪽에 있는 이름(변수)에 할당합니다.

- 변수는 어떤 값이 할당될 때 생성됩니다.

- 여기에서 파이썬은 변수 `age`에 숫자를 할당하고, 변수 `first_name`에 따옴표로 묶인 이름을 할당합니다.
  
  ```{python}
  age = 42
  first_name = 'Ahmed'
  ```

## `print`를 사용하여 값을 화면에 출력하세요.

- 파이썬에는 항목들을 텍스트로 인쇄하는 `print`라는 내장 함수가 있습니다.
- 함수의 이름을 사용하여 함수를 호출합니다(즉, 파이썬에게 함수를 실행하도록 지시합니다).
- 괄호 안에 함수에 제공할 값(즉, 인쇄할 항목)을 넣습니다.
- 출력에 문자열을 추가하려면 문자열을 작은따옴표나 큰따옴표로 묶으세요.
- 함수에 전달되는 값을 **인수(arguments)** 라고 합니다.

```{python}
print(first_name, 'is', age, 'years old')
```

- `print`는 항목들을 구분하기 위해 항목들 사이에 자동으로 공백을 추가합니다.
- 그리고 출력이 끝나면 줄바꿈(새 줄)을 합니다.

## 변수는 사용하기 전에 생성되어야 합니다.

- 변수가 아직 존재하지 않거나 이름을 잘못 입력한 경우, 파이썬은 오류를 보고합니다. (기본값을 "추측"하는 일부 다른 프로그래밍 언어들과는 다릅니다.)

```{python}
print(last_name)
```

- 오류 메시지의 마지막 줄이 대개 가장 유용한 정보를 담고 있습니다.
- 오류 메시지에 대해서는 [나중에](17-scope.md#reading-error-messages) 자세히 살펴볼 것입니다.

::::::::::::::::::::::::::::::::::::::::  callout

## 변수들은 셀을 넘나들며 유지됩니다.

Jupyter 노트북에서는 셀이 배치된 순서가 아니라 셀이 실행된 *순서* 가 중요하다는 점을 명심하세요. 파이썬은 노트북 내에서의 순서와 상관없이, 이전에 실행되었던 *모든* 코드(생성해 둔 변수 포함)를 기억합니다. 따라서 노트북 아래쪽에서 변수들을 정의한 다음 더 위쪽에 위치한 셀들을 (다시) 실행하더라도, 밑에서 정의했던 변수들은 여전히 메모리 상에 나타납니다. 한 가지 예로, 다음 두 내용을 포함하는 셀을 이 순서대로 작성해봅시다:

```{python}
print(myval)
```

```{python}
myval = 1
```

위에서부터 아래로 순서대로 실행한다면 첫 번째 셀은 에러를 낼 것입니다. 그러나, 두 번째 셀을 실행한 *후에* 다시 첫 번째 셀을 구동시키면 `1`이라고 똑똑히 출력할 것입니다. 혼란을 방지하기 위해 `Kernel` -> `Restart & Run All` 옵션을 활용하면 기존의 변수 기억 공간을 깨끗하게 청소하고 코드를 최상단부터 순서대로 재실행해 주어 도움이 될 수 있습니다.

::::::::::::::::::::::::::::::::::::::::::::::::::

## 변수들은 각종 계산식에 사용할 수 있습니다.

- 변수를 마치 원래의 값 그 자체인 것처럼 여러 계산식 안에서 그대로 쓸 수 있습니다.
  - 방금 전 몇 줄 위에서 `age` 변수에 `42` 라는 값을 집어넣었음을 기억해 보세요.

```{python}
age = age + 3
print('Age in three years:', age)
```

## 인덱스(Index)를 사용하여 문자열(string)에서 문자 하나를 뽑아냅니다.

- 문자열 내의 문자(개별 알파벳, 숫자 기호 등등)는 고유한 순서를 지닙니다. 예를 들자면 문자열 `'AB'`는 `'BA'`와 다릅니다. 이 순서 특징 덕분에, 우린 문자열을 문자들이 쭉 늘어선 목록 리스트처럼 취급할 수 있습니다.
- 문자열 내부의 각각 위치(첫 번째, 두 번째 등)에는 고유 번호가 주어집니다. 이 특정 번호를 가리켜 **인덱스(index)** 또는 하위 첨자(subscript)라고 부릅니다.
- 인덱스는 0번부터 시작하여 숫자를 매깁니다.
- 추출하고픈 위치의 인덱스 번호를 대괄호 안에 집어넣으면 그 지점의 문자 하나를 낚아챌 수 있습니다.

![A line of Python code, print(atom\_name[0]), demonstrates that using the zero index will output just the initial letter, in this case 'h' for helium.](fig/2_indexing.svg)

```{python}
atom_name = 'helium'
print(atom_name[0])
```

## 슬라이스(Slice)를 활용해 문자열의 일부(부분 문자열)를 조각냅니다.

- 한 문자열의 특정 일부 조각을 일컬어 **부분 문자열(substring)** 이라 부릅니다. 이 부분 문자열은 문자 단 1개짜리일 수도 있습니다.
- 어떤 리스트 안에 들어있는 아이템을 원소(element)라고 합니다. 우리가 문자열을 일종의 리스트 취급할 때, 이 문자열 안의 원소들은 곧 개별 문자 하나하나가 되는 셈입니다.
- 슬라이스(slice) 조각은 어떤 문자열(더 넓게는 리스트 비슷한 어떤 것이든)의 일부분을 지칭합니다.
- `[start:stop]` 형태의 표기법을 통해 이 슬라이스를 발라냅니다. 여기서 `start`는 우리가 얻고 싶은 파트의 첫 번째 목표물의 정수 인덱스 번호이며, `stop`은 우리가 추출하고 싶은 마지막 목표물의 그 *바로 다음 칸* 정수 인덱스를 의미합니다.
- `stop`에서 `start` 번호를 뺀 값은 곧 그 자른 슬라이스 조각의 총 길이가 됩니다.
- 슬라이스로 잘라내는 작업을 한다고 해서 원래 문자열에 상처가 나거나 변질되는 건 아닙니다. 대신 원본 문자열의 일부 범위를 복붙한 복사본을 결과로 내놓습니다.

```{python}
atom_name = 'sodium'
print(atom_name[0:3])
```

## 자체 내장된 함수 `len`을 동원하여 문자열의 총 길이를 확인합니다.

```{python}
print(len('helium'))
```

- 일반 산수 계산처럼, 중첩된 함수가 있을 때는 안쪽 기능부터 평가 해석되어 실행됩니다.

## 파이썬은 대소문자를 엄격하게 구분합니다.

- 파이썬은 대문자와 소문자를 완전히 다른 문자로 인식하기 때문에, `Name`과 `name`은 별개의 두 가지 변수로 취급됩니다.
- 프로그래밍에서 변수명의 첫 글자를 대문자로 시작하는 데에는 별도의 관례가 있으므로, 당분간은 변수명을 소문자로만 작성하는 것을 권장합니다.

## 의미를 알기 쉬운 이름으로 변수명을 지어줍시다.

- 파이썬 입장에서는 제약 규칙(영문, 숫자, 밑줄 기호만 허용 등)만 준수한다면 변수 이름을 어떻게 짓든 상관하지 않습니다.

```{python}
flabadab = 42
ewr_422_yY = 'Ahmed'
print(ewr_422_yY, 'is', flabadab, 'years old')
```

- 하지만 코드를 읽는 다른 사람들이 프로그램의 의도를 금방 파악할 수 있도록 의미 있는 이름으로 변수명을 짓는 습관을 들이는 것이 좋습니다.
- 왜냐하면 여러분의 코드를 가장 많이 읽게 될 "다른 사람" 중 한 명은 바로 미래의 나 자신일 것이기 때문입니다.

:::::::::::::::::::::::::::::::::::::::  challenge

## 두 변수의 값 맞교환(swap)하기

아래 표는 각 줄의 명령이 *실행 처리된 직후*의 변수 값들을 보여줍니다. 표의 빈칸을 직접 채워보세요.

```{python}
# 명령(Command)       # x의 값          # y의 값          # swap의 값
x = 1.0               #              #              #               
y = 3.0               #              #              #               
swap = x              #              #              #               
x = y                 #              #              #               
y = swap              #              #              #               
```

:::::::::::::::  solution

## 해답

위의 마지막 세 줄은 변수 `swap`을 임시 보관소로 사용하여 `x`와 `y` 변수가 가진 값들을 서로 맞교환하는 과정을 보여줍니다. 사실 이러한 방식은 프로그래밍에서 매우 흔하게 사용되는 패턴입니다.

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 결과값 예측해보기

다음 코드의 맨 마지막 줄이 실행된 시점에서, `position` 변수에 최종적으로 저장되어 있을 문자열 값은 무엇일까요? (코드를 실행해서 답을 확인하기 전에 먼저 결과를 스스로 예측해 보세요.)

```{python}
initial = 'left'
position = initial
initial = 'right'
```

:::::::::::::::  solution

## 해답

```{python}
print(position)
```

처음에 `initial` 변수에는 문자열 `'left'`가 할당되었습니다.
바로 다음 줄에서, `position` 변수는 `initial` 변수가 가진 값인 `'left'`를 할당받게 됩니다.
그리고 세 번째 줄에서 `initial` 변수에는 `'right'`라는 새로운 문자열 값이 할당되지만, 이전에 값이 할당되었던 `position` 변수는 그에 영향을 받지 않고 기존 값인 `'left'`를 그대로 유지합니다.

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 도전 과제 (Challenge)

만약 여러분이 변수에 `a = 123` 이라고 숫자를 할당해 두었을 때,
`a`에서 두 번째 위치에 있는 문자를 추출하기 위해 `a[1]` 명령을 실행하면 어떤 오류가 발생할까요?

:::::::::::::::  solution

## 해답

숫자는 문자열(string)처럼 순서가 있는 목록(sequence) 데이터 형식으로 이루어져 있지 않기 때문에, 파이썬은 숫자 타입 객체를 대상으로 인덱싱을 시도할 경우 다음과 같이 'TypeError'를 띄웁니다: `TypeError: 'int' object is not subscriptable` (int 객체는 구독(인덱싱)할 수 없음). [데이터 타입과 타입 변환 관련 수업](03-types-conversion.md)에서 우리는 이러한 데이터 타입과 다른 타입 간의 변환 방법들을 배우게 됩니다. 만약 여러분이 어떤 긴 숫자값에서 N번째 자릿수의 낱개 숫자를 뽑아내고 싶다면, `str` 내장 함수를 활용해 해당 숫자를 문자형(string)으로 변환한 뒤 특정 문자 열 데이터 위에서 인덱싱 조작을 처리하시면 됩니다.

```{python}
a = 123
print(a[1])
```

```{python}
a = str(123)
print(a[1])
```

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 작명하기 연습

어떤 변수의 이름을 지을 때 `m`, `min`, `minutes` 중 어떤 것이 가장 적합할까요? 이유는 무엇인가요?
힌트: 만일 코드 작성자가 연구실을 떠나게 되어 다른 사람이 아래와 같은 형식의 코드를 물려받았을 때, 다음 중 어떤 형태를 더 선호하게 될지 상상해 보세요:

1. `ts = m * 60 + s`
2. `tot_sec = min * 60 + sec`
3. `total_seconds = minutes * 60 + seconds`

:::::::::::::::  solution

## 해답

셋 중에서는 `minutes`가 가장 적절한 이름입니다. 왜냐하면 `min`이라는 단어는 최솟값(minimum)을 의미하는 약어로 쉽게 오해될 수 있기 때문입니다. 게다가 파이썬에는 최솟값을 구하는 내장 함수 이름이 이미 `min`으로 예약되어 있어, 추후 이 변수명과 이름 충돌이 일어날 위험성도 안고 있습니다. 반면 `total_seconds = minutes * 60 + seconds` 처럼 작성하면 코드의 목적을 누구나 명확히 알 수 있습니다.

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 자르고 베기 (Slicing) 연습해보기

다음 파이썬 명령어는 화면에 무엇을 출력해 낼까요?

```{python}
atom_name = 'carbon'
print('atom_name[1:3] is:', atom_name[1:3])
```

:::::::::::::::  solution

## 해답

`atom_name[1:3] is: ar` 가 출력됩니다. 인덱스 `1` (두 번째 글자 'a') 부터 시작하여 인덱스 `3` 직전 (세 번째 글자 'r') 까지의 슬라이스 복사본이 반환됩니다.

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 자르고 베기 (Slicing) 의 원리 파악

여기 아주 긴 식물 학명 종류가 나열된 문자열 데이터가 주어졌습니다:

```{python}
species_name = "Acacia buxifolia"
```

각각의 명령어 식을 실행하면 어떤 문자가 잘려 나와 보일지 예상해 보세요:

1. `species_name[2:8]`
2. `species_name[11:]` (콜론 표기법 구역 끝에 닫혀야 할 숫자값이 누락된 상태)
3. `species_name[:4]` (콜론 좌측 위치 첫 출발값이 누락된 상태)
4. `species_name[:]` (콜론의 양 끝이 모두 비어있는 경우)
5. `species_name[11:-3]`
6. `species_name[-5:-3]`
7. 만일에 이 슬라이스를 저며 분할하려는 멈춤 마지노선인 `stop` 지점 인덱스 수치가 문자열의 기존 길이를 초과해버리면 어떻게 될까요? (예: `species_name[0:20]` 혹은 `species_name[:103]`)

:::::::::::::::  solution

## 해답

1. `species_name[2:8]` 은 부분 문자열 `'acia b'` 조각을 반환합니다.
2. `species_name[11:]` 은 끝점이 지정되지 않았기 때문에 인덱스 11번 위치부터 맨 마지막 부분까지를 완전히 잘라와서 `'folia'` 라는 부분만 반환합니다.
3. `species_name[:4]` 은 맨 출발점 구역(인덱스 0)부터 4번째 위치하기 바로 직전(인덱스 3) 자리값까지를 잘라내어 `'Acac'`문자열을 반환합니다.
4. `species_name[:]` 은 위아래로 한계선 제어 값이 하나도 설정되지 않은 탓에 문자 원본 껍데기 그대로 `'Acacia buxifolia'` 통 문자열 전체 내용물 복사본을 반환합니다.
5. `species_name[11:-3]` 인덱스의 경우 양의 정수뿐만 아니라 마이너스 기호를 통해 문자열 맨 뒤부터 역순으로 위치 번호를 세는 것도 가능합니다. 때문에 11번 인덱스 위치(f)에서부터 뒤에서 3번째 문자 직전까지 슬라이스하여 `'fo'` 영역만 반환해 줍니다.
6. `species_name[-5:-3]` 또한 마찬가지로, 맨 뒤에서 역순으로 다섯 칸 앞으로 온 라인 위치에서 거꾸로 세 칸 앞 직전 위치 구역까지 잘라서 `'fo'` 란 문자가 남습니다.
7. 만약 끝점을 설정하는 자릿수 값 범위가 원래 허용 길이를 한참 뛰어넘어 초과 설정된 상태의 슬라이스를 명령한다고 할지라도 파이썬 엔진은 에러를 일으키지 않습니다. 오류 발생의 지연 없이, `species_name[0:20]`의 결과물은 그저 안전하게 문자열 끝단에 부딪혀 멈추게 되어 `species_name[0:]`과 완전히 똑같은 결과를 돌려줍니다. 비슷하게 `species_name[:103]`는 `species_name[:]`의 결과물 상태와 차이 없이 원본 데이터와 동일하게 무사 반환됩니다.
  
::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: keypoints

- 변수를 사용하여 값을 저장하세요.
- `print` 명령을 사용하여 저장한 변수의 내용물 데이터를 화면에 출력해 보세요.
- 한번 생성되어 변수에 할당된 내용물들은 셀들을 오가면서도 값이 유지됩니다.
- 선언, 정의된 적이 있는 변수에 한해서만 불러서 사용할 수 있습니다.
- 이 변수들은 다양한 계산식과 조합해 활용 응용할 수 있습니다.
- 인덱스 식 번호를 집어넣어, 긴 배열의 문자열 단어들로부터 문자 알파벳 한 글자를 건져 올릴 수 있습니다.
- 슬라이스(Slice) 기능을 사용하여 길다란 문자열 안에서 특정 글자 범위 영역 조각만을 분리 추출할 수 있습니다.
- 파이썬 내장 기능 함수 `len`을 빌려 활용하면 해당 문자열 데이터 배열의 전체 길이를 계산할 수 있습니다.
- 파이썬 프로그래밍 언어는 알파벳의 소문자, 대문자 구분에 굉장히 엄격합니다.
- 변수 이름을 지을 때는 코드를 짠 의도를 파악하기 쉬운 명확하고 합리적인 이름을 붙여주는 좋은 버릇을 가지면 도움이 됩니다.

::::::::::::::::::::::::::::::::::::::::::::::::::
