---
title: 내장 함수와 도움말
teaching: 15
exercises: 10
---

::: {.callout-tip title="학습 목표"}

- 함수의 목적을 설명할 수 있습니다.
- 파이썬 내장 함수를 올바르게 호출할 수 있습니다.
- 내장 함수 호출을 중첩하여 올바르게 사용할 수 있습니다.
- 도움말(help) 기능으로 내장 함수에 관한 사용 문서를 조회할 수 있습니다.
- SyntaxError와 NameError가 발생하는 상황을 바르게 파악하고 묘사할 수 있습니다.

:::

::: {.callout-note title="질문"}

- 내장 함수는 어떻게 사용하나요?
- 함수가 어떤 동작을 하는지 어떻게 알아낼 수 있나요?
- 프로그래밍 중에 어떤 종류의 오류가 발생할 수 있나요?

:::

## 주석(Comments)을 활용해 프로그램에 대한 설명문을 추가해 보세요.

```{python}
# 이 문구는 파이썬에서 시스템적으로 실행되지 않습니다.
adjustment = 0.5   # 여기도 마찬가지입니다 - '#' 기호 뒤에 서술된 내용들은 모두 기계가 무시합니다.
```

## 함수는 0개 이상의 인수를 받을 수 있습니다.

- 우리는 이미 몇 가지 함수들을 사용해 보았습니다. 이제 함수가 어떻게 동작하는지 좀 더 자세히 알아보겠습니다.
- 함수에 전달하는 특정한 값을 *인수(Argument)* 라고 부릅니다.
- `len` 함수는 정확히 하나의 인수만을 받습니다.
- `int`, `str`, `float` 함수들은 기존 데이터의 형식을 변환하여 완전히 새로운 값으로 만들어 반환합니다.
- `print` 함수는 인수를 아예 받지 않을 수도 있고, 여러 개의 인수를 한 번에 받을 수도 있습니다.
- 만약 아무 인수도 주지 않고 `print()`를 호출하면, 단순히 내용이 없는 빈 줄 하나를 출력합니다.
  - 전달할 인수가 없더라도 뒤쪽의 소괄호(`()`)는 반드시 작성해야 파이썬 엔진이 이를 변수가 아닌 함수 호출로 인식합니다.

```{python}
print('before')
print()
print('after')
```

## 모든 함수는 결과를 반환(Return)합니다.

- 함수를 호출하면 반드시 어떤 형태로든 결괏값을 반환합니다.
- 만약 함수가 특별히 유용한 값을 계산하여 돌려주지 않는다면, 파이썬의 특수한 빈 값인 `None`을 반환합니다. `None`은 파이썬에서 '값이 없음(Nothing)'을 나타내기 위해 사용하는 공식적인 특수 객체입니다.

```{python}
result = print('example')
print('result of print is', result)
```

## 일상적으로 자주 쓰이는 내장 함수로는 `max`, `min`, `round` 등이 있습니다.

- 주어진 여러 값 중에서 가장 큰 값을 찾을 때는 `max` 함수를 사용합니다.
- 반대로 가장 작은 값을 찾고 싶을 때는 `min` 함수를 사용합니다.
- 이 두 함수는 숫자 데이터뿐만 아니라 문자열에서도 잘 작동합니다.
  - 문자열에서 크고 작음을 판단하는 기준은 보통 사전순(0-9, A-Z, a-z 순) 정렬 규칙을 따릅니다.

```{python}
print(max(1, 2, 3))
print(min('a', 'A', '0'))
```

## 함수는 특정 타입의 인수가 주어졌을 때만 동작할 수 있습니다.

- `max`와 `min` 함수는 최소한 하나 이상의 인수를 받아야 합니다.
  - 빈 괄호 안에서 가장 큰 값이나 가장 작은 값을 찾을 수는 없기 때문입니다.
- 또한 전달된 인수들이 서로 크기를 비교할 수 있는 적절한 타입이어야 합니다.

```{python}
print(max(1, 'a'))
```

## 일부 함수는 선택적인 인수를 위해 기본값(Default values)을 가지고 있습니다.

- `round` 함수는 숫자를 반올림해 줍니다.
- 별도의 추가 인수를 지정하지 않으면, 기본적으로 소수점 아래를 완전히 버린 정수 형태로 반올림합니다.

```{python}
round(3.712)
```

- 원한다면 두 번째 인수를 통해 소수점 몇째 자리까지 반올림할지 명시적으로 지정할 수 있습니다.

```{python}
round(3.712, 1)
```

## 객체에 종속되어 호출되는 특수한 형태의 함수를 메서드(Methods)라고 부릅니다.

- 차후 살펴볼 Pandas 강의 단원 등에서 이러한 형태의 함수 호출을 자주 접하게 될 것입니다.
- 메서드(Methods) 역시 일반 함수처럼 호출 시 소괄호 기호가 필요하지만, 함수의 이름이 독립적으로 쓰이는 대신 데이터 객체(변수 등)의 이름 뒤에 점(`.`)을 찍고 이어집니다.
- 가끔 파이썬 내부 동작과 관련된 특수 메서드들은 이름 양 끝에 이중 밑줄(double underscores) 표기가 붙어 있는 형태를 보입니다.

```{python}
my_string = 'Hello world!'  # 먼저 문자열을 생성합니다.

print(len(my_string))       # 일반적인 len 함수는 괄호 안에 대상 값을 통째로 넘겨받아 길이를 추출합니다.

print(my_string.swapcase()) # 이 방식은 원본 my_string 변수 객체의 뒤쪽에 직접 점을 찍고 .swapcase() 라는 메서드를 호출한 형태입니다.

print(my_string.__len__())  # 사실 len(my_string)의 내부 동작은 my_string 객체의 내부 특수 메서드인 __len__()을 호출하는 구조로 되어있습니다.

```

- 종종 여러 개의 메서드 호출이 줄줄이 이어지는 "체이닝(Chained)" 구조를 볼 수 있습니다. 이 경우 평범하게 읽는 순서와 동일하게 왼쪽에서 오른쪽으로 차례차례 평가되고 동작합니다.

```{python}
print(my_string.isupper())          # 문자열 안의 문자가 모두 대문자인지 판단 (모든 글자가 대문자는 아니므로 False)
print(my_string.upper())            # 이 메서드는 해당 문자열을 일괄 대문자로 변환한 새 문자열을 반환합니다.

print(my_string.upper().isupper())  # 먼저 upper()가 문자열을 모두 대문자로 만든 뒤, 결과물에 대해 isupper()를 다시 묻기 때문에 True가 됩니다.
```

## 내장 함수 `help` 를 통해 도움말을 확인해 봅시다.

- 파이썬에 기본적으로 포함된 모든 내장 함수들은 자체적인 세부 설명서(문서)를 가지고 있습니다.

```{python}
help(round)
```

## Jupyter Notebook 환경에서는 단축키를 활용하여 도움말을 더 편리하게 확인할 수 있습니다.

- 방법 1: 도움말을 확인하고 싶은 함수 이름 위나 괄호 안에 커서를 둡니다.
  - <kbd>Shift</kbd> 키를 누른 상태에서 <kbd>Tab</kbd> 키를 누릅니다.
  - 도움말 창을 확장하려면 그 상태에서 <kbd>Tab</kbd> 키를 여러 번 누르면 됩니다.
- 방법 2: 노트북 셀에 함수 이름을 적은 뒤 그 바로 뒤에 물음표(`?`)를 붙입니다. 이후 해당 셀을 실행(Run)하면 도움말 패널이 열립니다.

## 문법이 올바르지 않아 파이썬이 코드를 이해할 수 없을 때 이를 구문 오류 `Syntax error` 라고 부릅니다.

- 구문 오류가 발생하면 파이썬은 코드를 읽지 못하므로 실행 자체를 거부합니다.

```{python}
# 문자열을 시작할 때 여는 따옴표는 있지만, 닫는 따옴표를 누락했습니다.
name = 'Feng
```

```{python}
# 변수 할당 시 등호(`=`)는 하나여야 하지만 두 개를 연달아 사용했습니다.
age = = 52
```

- 오류 메시지를 조금 더 자세히 파헤쳐 볼까요:

```{python}
print("hello world"
```

- 메시지는 구문 분석 시스템이 첫 번째 줄("line 1")부터 문제를 발견했음을 알려줍니다.
  - `ipython-input` 문구는 현재 사용 중인 대화형 해석기(Jupyter 등) 환경 안으로 코드가 입력되었음을 표시합니다.
- 다음의 `-6-` 부분은 에러가 6번째 셀의 상호작용 지점에서 발생했음을 보여줍니다.
- 에러 메시지는 문제가 확인된 코드 줄 원본을 보여주며, `^` 캐럿 기호를 사용해 문장 내부에서 파싱이 잘못된 지점을 시각적으로 지목합니다.

## 문법은 올바르지만 실행 도중에 오류가 발생하는 경우 파이썬은 실행 오류 `Runtime error` 를 보고합니다. {#runtime-error}

```{python}
age = 53
remaining = 100 - aege # 작성자가 'age'의 스펠링을 잘못 입력했습니다.
```

- 구문 오류(Syntax errors)는 원본 소스 코드의 입력 형식이 파이썬 문법에 맞게 작성되었는지 텍스트를 읽어가며 확인해 수정하고, 실행 오류(Runtime errors) 건들은 오류 메시지의 원인 경로를 추적하여 프로그램 진행 과정 중 어디에서 잘못된 값이 발생했는지 논리 구조를 추적해 보완하시면 됩니다.

## 코딩 중 막혔을 때 참고할 수 있는 외부 자원들

프로그래머들은 종종 자신이 작성한 코드에서 오류를 해결하기 위해 다음과 같은 방법들로 도움을 받습니다.

* 온라인 검색 엔진 활용:
  오류 메시지의 마지막 줄이나 핵심 단어를 복사하여 "python"이라는 설명 단어와 함께 검색 엔진에 붙여넣어 보세요. 그리고 겪고 있는 현상을 짧게 묘사해 보세요.
  동일한 문제를 앞서 겪었던 수많은 다른 사람들의 글과 해결책을 찾을 수 있을 것입니다.
    * 개발 관련 질문/답변 커뮤니티인 [StackOverflow](https://stackoverflow.com/questions) 홈페이지가 특히 유용합니다: 질문에 대한 답변들이 단순히 최신순이 아니라 커뮤니티 투표 추천 수에 따라 위로 랭크되어 노출되므로 양질의 답변을 얻기 쉽습니다.
    * **주의사항:** 게시된 답변 코드를 완벽하게 이해하지 못한 상태에서 무작정 복사하여 자신의 코드에 붙여넣는 일은 코드를 통제 불가능한 상태로 만들 수 있으므로 피해야 합니다.
* 주변 사람에게 묻기:
  주변에 코딩 경험이 더 많은 선배나 동료가 있다면, 문제를 설명하고 조언을 구하세요.
* 소리 내어 직접 설명해 보기:
  작성한 코드가 무엇을 수행해야 하는지 하나하나 말로 설명하다 보면 오류의 원인을 스스로 깨닫는 경우가 많습니다.
  전문 프로그래머들 사이에서는 이를 가리켜 ["고무 오리 디버깅 기법 (Rubber duck debugging)"](https://en.wikipedia.org/wiki/Rubber_duck_debugging) 이라고 부릅니다.

### 챗봇(Generative AI)의 도입과 활용 지침


### 생성형 AI 섹션의 강의에 관한 참고 사항
이 생성형 AI 소개 단락은 간단한 개괄을 위해 마련되었습니다. 워크숍 분위기나 시간 여유에 따라 수강생들과 보다 심도 있는 대화를 나누는 시간을 가질 수도 있습니다.
강사 본인의 지식 수준과 윤리적 논쟁 이슈들에 기반하여 자율적인 방식으로 교육할 수 있습니다:

* 대형 언어 모델(LLMs)이 어떠한 알고리즘을 사용해 결괏값을 예측하는지에 대해 설명하고, 이것이 기존에 사용되던 지식 검색 도구와 어떻게 다른지 알려 줍니다 (결국 기술은 사람처럼 온전한 사고 판단론적 추론을 통해 작동하는 것이 아님 등).
* 실습 과정에서 실제로 이러한 AI 도구들을 사용해 보고 싶어 하는 수강생들을 위해 권장할 만한 타당한 활용 예시를 보여 줍니다.
* 생성형 AI가 가진 투명성과 윤리적 책임 이슈를 환기하고, 코더로서 현업에서 이를 언제 어떻게 사용할지에 대해 진지한 성찰을 하도록 논의를 발전시킵니다.

AI 생태계의 흐름은 굉장히 빠르게 변화하고 있습니다. 만일 강사님께서 이 섹션을 진행하시려 할 때 교재 내용이 최신 동향을 반영하지 못하고 있다면, 언제든지 깃허브 원본 리포지토리에 이슈를 제기(open an issue)하시거나 풀 리퀘스트(pull request)를 올려 교재 업데이트에 참여해 주시면 감사하겠습니다.


코드 작성을 하다가 오류를 해결하거나 아이디어를 짜낼 때 챗GPT 같은 _생성형 AI 봇(generative AI chatbots)_ 과 같은 최신 기술 플랫폼들을 활용하는 사람이 점점 많아지고 있습니다.
이러한 챗봇 환경에 에러 메시지를 복사해 넣고 증상을 호소하면, 꽤 설득력 있는 해결 방안을 손쉽게 받을 수도 있습니다.
다만, 이 도구가 기존 인터넷 정보망과 전혀 다른 작동 원리를 가졌다는 점을 인지할 필요가 있습니다.
StackOverflow와 같은 전통적인 포럼들의 답변은 실제 '사람(human)'이 여러 시행착오 지식을 공유한 기록일 확률이 높습니다.
하지만 생성형 AI가 텍스트를 구성하는 그 기저 작용은 방대한 코퍼스 통계와 훈련된 수학적 확률 확률론입니다. 프롬프트 질의가 주어지면, 사전 학습 데이터를 기반으로 단어 출현 확률 분포상 가장 자연스럽고 응답 확률이 높은 _추세 나열체 조합(most likely sequence)_ 을 계산해 뱉어낼 따름입니다.

비록 그러한 챗봇의 방대한 응답이 여러분에게 긴급한 문제 해결 실마리를 줄지라도, 그 내용물이 절대적으로 신뢰할 만하다고 믿어선 곤란합니다. AI 산출물은 겉보기엔 매우 그럴듯해 보이지만 정작 알맹이가 완전히 틀렸거나 허위가 된 정보를 정답인 양 늘어놓을 수 있습니다(이를 흔히 '환각 현상'이라고 부릅니다). 결국 챗봇에서 얻은 정보는 여타 구글링 지식 검색 지침들과 마찬가지로 반드시 사용자가 직접 내용을 판독하고 신뢰성을 검증해야 합니다.
사용자는 챗봇의 응답 문장들을 낱낱이 파악하여 그 답변 논리 구조의 모순이나 결함 유무를 가늠할 수 있어야 하며, 제공받은 답변 코드에 섞여 있을 예기치 않은 버그들을 직접 보완하거나 고치고 조치할 수 있는 기본적인 프로그래밍 배경지식을 갖춰야만 합니다.

오류 극복 외에도 수많은 현역 프로그래머는 새 코드 뼈대의 스케치를 챗봇에게 작성 초벌 시키거나, 기존 코드 자산을 리팩토링하고 보완하거나, 타 개발 언어로 컨버팅하는 등의 보조 작업은 물론 검색에 사용할 알맞은 탐색 키워드를 묻는 용도로도 이들을 활용하고 있습니다. 그러나 의존성만큼이나 주의할 내재적 위험성들도 많이 숨어있음을 명심하시길 바랍니다.

기존 챗봇들이 채택한 근본 핵심 모델들은 인터넷 상의 수많은 텍스트 데이터 사료들을 대거 수집하여 병합한 거대 용량 데이터를 기반으로 “지도 학습 훈련(trained)”된 시스템입니다. 따라서 생성 결과물은 필연적으로 옛 시절에 오염된 부정확 정보 데이터나, 편향적이거나 부적절한 관념들을 그대로 재생산(recapitulate)해버릴 수도 있습니다.
게다가 이를 학습시키기 위해 천문학적으로 사용되는 데이터 센터 구동 전력 소비나 물 절삭 환경 부담률은 이 대형언어모델(LLMs)이 피할 수 없는 불편한 환경 비용입니다. 단순히 새 모델의 트레이닝 국면을 떠나 일반인 유저가 소규모 질문 질의 응답 요청을 실행(inference)할 때마저도 엄청난 비용이 감내되고 있습니다. LLM 시스템이 야기하는 생태 환경 부담 영향력에 관한 전문가 의견이 궁금하시다면 HuggingFace 등에서 정리한 [초심자를 위한 AI 환경 영향 가이드 (AI Environmental Impact Primer)](https://huggingface.co/blog/sasha/ai-environment-primer) 등의 웹사이트 글들을 읽어보십시오.
설상가상으로 기존 훈련 사료 모델 취합의 투명성, 데이터의 저작권 및 획득 정당성에 대한 책임 공방은 거센 비판과 논란을 남기고 있습니다. 게다가 개발 초창기에는 제3세계의 저임금 노동력 착취(막후 데이터 라벨링 작업 등) 부조리까지 더해져 그 윤리 공방의 파장을 가중시킨 현실도 존재합니다.

따라서 코스 지도 강사진들은 **본 워크숍 학습 과정에 참여하시는 동안은 외부 생성형 AI 챗봇의 개입이나 도움받기를 우회하시고 직접 문제를 대면하시기를 거듭 권고합니다**. 그 주된 이유는 다음과 같습니다:

1. 초보자 입문자 단계에서 조우하게 될 대다수의 일반적인 오류 증상들은 사실상 웹 검색 엔진의 상단 몇 페이지 노출 검색 결과만으로도 속 시원히 해결 설명될 수 있을 정도로 이미 관련 자료 접근성이 매우 높습니다.
2. 당신이 우리 코스의 기초 문법들을 한 번 한 번 자력으로 수정해 나갈 때 축적되는 지식 파운데이션 기틀은, 나중에 낯선 웹의 정보 파편들이나 AI가 만든 생성 코드 구문 따위가 안전하고 정확한 형태인지를 홀로 심판하고 걸러낼 때 매우 결정적으로 필요한 필수 분석 시약 자산이 될 것입니다. 
   향후 자발적으로 챗봇 도구들을 도우미로 기용하기로 판단한다고 하더라도, 사전에 먼저 충분히 다져둔 굳건한 배경 지식이야말로 이들을 더욱 배가된 효과 효율의 실전 무기로써 통제하고 부릴 수 있는 진정한 기술의 차이를 판가름할 원동력이 됩니다.
3. 여러분이 코딩 초입 단계에서 부닥칠 오류의 고비들은 과거 다른 프로그래머 생존 선배들이 수없이 저지르고 고민했던 오류 투성이 경험과 매우 일치하는 흔한 발자취입니다. 당신의 이런 빈출 에러 패턴들은 챗봇 로봇을 교육하는데 쓰인 '훈련 데이터 저장소'에서도 과도 표집으로 쌓여있을 가능성이 다분합니다.
   이는 생성형 요술 챗봇들이, 유독 초심자가 겪는 종류의 뻔한 오류들에 대해서는 기가 막힐 정도로 완벽한 해답을 술술 매끄럽게 답변한다는 점을 역으로 방증합니다. 때문에 여러분은 이 챗봇 체제가 마치 전능한 척, 향후 훨씬 어렵고 복잡하게 꼬인 전문 과제를 떠맡길 단계에서도 변함없이 모든 것을 알아서 해결해 주고 책임져 줄 도구라며 허황한 신뢰 착각(false impression)과 지나친 의존증에 빠질 크나큰 오판 위험의 부작용에 처할 수 있습니다.


:::: {.callout-important title="범례"}

## 실행 순서 파악하기

1. 다음 프로그램에서 각 연산이 실행되는 순서를 간단한 말로 설명해 보세요:
  예를 들어, 덧셈은 언제 발생하며, 뺄셈은 언제 일어나는지,
  그리고 각 함수 호출은 어느 시점에 발생하는지 등입니다.
2. 실행을 모두 마친 후 변수 `radiance`가 최종적으로 가지게 되는 값은 무엇입니까?

```{python}
radiance = 1.0
radiance = max(2.1, 2.0 + min(radiance, 1.1 * radiance - 0.5))
```

::: {.callout-caution collapse="true" title="해답"}

## 해답

1. 연산 처리 순서는 다음과 같습니다:
  1. `1.1 * radiance = 1.1` (가장 안쪽의 곱셈 연산)
  2. `1.1 - 0.5 = 0.6` (그 결괏값을 이용한 뺄셈 연산)
  3. `min(radiance, 0.6) = 0.6` (안쪽 소괄호의 `min` 함수 호출)
  4. `2.0 + 0.6 = 2.6` (`min` 함수의 반환값에 대한 덧셈 연산)
  5. `max(2.1, 2.6) = 2.6` (가장 바깥쪽 소괄호의 `max` 함수 호출)
2. 모든 연산이 종료된 후 변수 `radiance`에 할당되는 최종값은 `2.6`입니다.
  
:::

::::

:::: {.callout-important title="범례"}

## 차이점 발견하기

1. 아래의 코드 단락 내에 있는 3개의 `print` 문이 각각 실행 시 어떤 결과를 출력할지 미리 예측해 보세요.
2. 만약 마지막 구문이 `print(max(len(rich), poor))` 처럼 쓰였다면 코드가 정상적으로 실행될까요, 아니면 오류(Error) 메시지를 발생시킬까요?
  만약 오류가 발생하지 않는다고 가정하더라도, 이 연산이 반환하는 결과물이 논리적으로 의미가 있는 일일지 생각해 보세요.

```{python}
easy_string = "abc"
print(max(easy_string))
rich = "gold"
poor = "tin"
print(max(rich, poor))
print(max(len(rich), len(poor)))
```

::: {.callout-caution collapse="true" title="해답"}

## 해답

```{python}
print(max(easy_string))
```

```{python}
print(max(rich, poor))
```

```{python}
print(max(len(rich), len(poor)))
```

`max(len(rich), poor)`와 같이 변경된 코드는 TypeError를 발생시킵니다. 왜냐하면 실제로 평가되는 형태가 `max(4, 'tin')`이 되기 때문입니다. 이전 내용에서 다루었듯이 정수형 데이터(integer)와 문자열 데이터(string)를 함께 동일 선상에 두고 크기를 비교하는 것은 파이썬 체계상 불가능하므로 의미가 없습니다.

:::

::::

:::: {.callout-important title="범례"}

## 에러가 발생하는 이유

왜 `max` 함수나 `min` 함수는 아무런 인자도 주지 않고 빈 괄호로 호출(`max()`)했을 때 단순히 `None`을 돌려주지 않고 에러를 발생시키는 것일까요?

::: {.callout-caution collapse="true" title="해답"}

## 해답

`max`와 `min`은 기본적으로 최소 하나 이상의 비교 대상(인수)이 필요하도록 내부적으로 설계되어 있습니다. 호출 시 이를 지키지 않았을 때는 잘못 사용된 것이므로 TypeError라는 오류를 적극적으로 발생시켜 줍니다.
만약 이런 명백히 잘못된 상황에도 시스템이 너그럽게 `None`을 반환하고 아무 일 없었다는 듯이 넘어가 준다고 가정해 봅시다. 그러면 이 `None` 값은 어딘가의 변수에 의도치 않게 할당될 것이고, 계속해서 코드가 돌아가다가 전혀 다른 뒷부분 시점에서 `None`을 두고 연산을 수행하려다 도무지 원인을 알 수 없는 엉뚱한 실행 오류(Runtime error)를 겪게 될 수 있습니다. 문제가 발생한 즉시 에러를 발생시켜 프로그래머에게 알려 주는 것이 버그를 추적하고 해결하는 데 훨씬 유리합니다.

:::

::::

:::: {.callout-important title="범례"}

## 문자열의 마지막 글자 추출하기

우리는 파이썬이 위치 인덱스 번호를 셀 때 무조건 0부터 시작한다는 사실과,
반면 `len` 함수는 문자열 안에 존재하는 문자의 총 수량을 반환한다는 사실을 함께 배웠습니다.
이 두 가지 원리를 조합해 볼 때, `name` 이라는 문자열 변수에서 제일 끝의 마지막 문자 한 글자를 정확히 추출해 내려면 어떤 위치 인덱스 표현식을 사용해야 할까요?
(참고: 이어지는 후속 단원에서는 이를 더욱 쉽게 수행할 수 있는 파이썬만의 고유한 꿀팁 인덱싱 기능을 추가로 배우게 됩니다.)

::: {.callout-caution collapse="true" title="해답"}

## 해답

`name[len(name) - 1]`

:::

::::

::: {.callout-note appearance="simple"}

## 공식 파이썬 문서(Docs)를 적극 활용하세요!

공식 [파이썬 온라인 도큐먼트(official Python documentation)](https://docs.python.org/3/) 문서는 이 프로그래밍 언어가 지원하는 모든 지식과 체계가 집대성된 훌륭한 참고 자료입니다. 특히 [내장 함수(Built-in Functions) 페이지](https://docs.python.org/3/library/functions.html)에는 이번 강좌에서 배운 함수들을 포함하여 기본적으로 제공되는 수많은 함수들의 카탈로그가 정리되어 있습니다. 초보자 입장에서는 다소 난해할 수 있는 기능들도 포함되어 있지만, 예상하지 못했던 간편하고 강력한 기능들을 제공하는 유용한 함수들도 숨어있으니 꼭 한번 살펴보시기 바랍니다.

:::

::: {.callout-note title="핵심 요약"}

- 주석(comments) 달기를 활용하여 프로그램 코드 구문 곳곳에 가독성을 돕는 작동 설명을 남겨 두세요.
- 함수는 그 종류의 성격에 따라 0개이거나 그 이상 복수의 여러 개의 인수를 받도록 만들어질 수 있습니다.
- 일상적으로 자주 쓰이는 내장 함수로는 `max`, `min`, `round` 등을 꼽을 수 있습니다.
- 특정 함수들은 특정 타입이나 조건에 알맞게 조합된 인수가 주어졌을 때만 정상적으로 작동합니다.
- 일부 함수들은 선택적으로 생략할 수 있는 인수들에 대해 기본값(default values)을 자체적으로 설정해 두고 있습니다.
- 내장 시스템 함수인 `help`를 호출하여 특정 함수들의 사용법과 설명서를 확인할 수 있습니다.
- 프로그래밍에서 함수를 한 번 호출하면 반드시 어떤 형태로든 결과물을 반환합니다.
- 파이썬이 코드를 읽다가 문법을 도무지 이해할 수 없을 때는 구문 오류 `Syntax error` 를 발생시킵니다.
- 프로그램의 문법 자체는 정상이라 한창 실행되던 도중 예기치 않은 결함으로 실행이 중단되는 상황에 직면하면 파이썬은 실행 오류 `Runtime error` 를 발생시킵니다.
- 구문 오류(Syntax errors)는 원본 소스 코드를 읽고 문법 구조를 점검하여 고치고, 실행 오류(Runtime errors)는 코드가 실행되어 왔던 과정을 거슬러 추적(tracing execution)하며 문제를 조사하고 보완해야 합니다.

:::
