---
title: 데이터를 데이터프레임으로 읽어오기
teaching: 10
exercises: 10
---

::::::::::::::::::::::::::::::::::::::: objectives

- Pandas 라이브러리를 임포트합니다.
- Pandas를 사용하여 간단한 CSV 데이터 세트를 불러옵니다.
- Pandas 데이터프레임에 대한 기본적인 정보를 얻습니다.

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: questions

- 표 형태의 데이터를 어떻게 읽을 수 있나요?

::::::::::::::::::::::::::::::::::::::::::::::::::

## 표 형태의 데이터에 대한 통계를 내기 위해 Pandas 라이브러리를 사용하세요.

- [Pandas](https://pandas.pydata.org/)는 통계, 특히 표 형태의 데이터를 다루는 데 널리 사용되는 파이썬 라이브러리입니다.
- R의 데이터프레임 기능에서 많은 부분을 차용했습니다.
  - 열(column)에 이름이 있고 서로 다른 데이터 타입을 가질 수 있는 2차원 표입니다.
- `import pandas as pd`를 사용하여 Pandas를 로드합니다. 별칭 `pd`는 코드에서 Pandas 라이브러리를 지칭할 때 흔히 사용됩니다.
- `pd.read_csv`를 사용하여 CSV(Comma Separated Values) 데이터 파일을 읽습니다.
  - 인수는 읽을 파일의 이름입니다.
  - 변수에 할당할 수 있는 데이터프레임을 반환합니다.

```{python}
import pandas as pd

data_oceania = pd.read_csv('data/gapminder_gdp_oceania.csv')
print(data_oceania)
```

- 데이터프레임의 열은 관측된 변수이고, 행은 관측치입니다.
- Pandas는 출력이 화면에 맞지 않게 너무 넓을 때 줄 바꿈을 표시하기 위해 백슬래시 `\`를 사용합니다.
- 설명이 포함된 데이터프레임 이름을 사용하면 여러 데이터프레임을 쉽게 구분할 수 있으므로 실수로 데이터프레임을 덮어쓰거나 잘못된 데이터프레임에서 읽는 것을 방지할 수 있습니다.

::::::::::::::::::::::::::::::::::::::::  callout

## 파일을 찾을 수 없음

우리 수업에서는 데이터 파일을 `data` 하위 디렉토리에 저장하므로 파일 경로가 `data/gapminder_gdp_oceania.csv`입니다.
만약 `data/`를 포함하는 것을 잊었거나, 포함했지만 파일 복사본이 다른 곳에 있는 경우, 다음과 같은 줄로 끝나는 [런타임 에러](04-built-in.md)를 얻게 됩니다.


::::::::::::::::::::::::::::::::::::::::::::::::::

## `index_col`을 사용하여 특정 열의 값을 행 제목으로 사용하도록 지정할 수 있습니다.

- 행 제목은 숫자입니다 (이 경우 0과 1).
- 국가별로 인덱싱하고 싶습니다.
- 이를 수행하려면 `read_csv`에 열 이름을 `index_col` 매개변수로 전달합니다.
- 데이터프레임 이름을 `data_oceania_country`로 지정하면 데이터가 포함된 지역(`oceania`)과 인덱싱되는 방식(`country`)을 알 수 있습니다.

```{python}
data_oceania_country = pd.read_csv('data/gapminder_gdp_oceania.csv', index_col='country')
print(data_oceania_country)
```

## 데이터프레임에 대해 자세히 알아보려면 `DataFrame.info()` 메서드를 사용하세요.

```{python}
data_oceania_country.info()
```

- 이것은 `DataFrame`입니다.
- `'Australia'`와 `'New Zealand'`라는 이름의 두 행이 있습니다.
- 12개의 열이 있으며 각 열에는 2개의 실제 64비트 부동 소수점 값이 있습니다.
  - 누락된 관측치를 나타내는 데 사용되는 null 값에 대해서는 나중에 설명하겠습니다.
- 208바이트의 메모리를 사용합니다.

## `DataFrame.columns` 변수는 데이터프레임의 열에 대한 정보를 저장합니다.

- 이것은 메서드가 *아니라* 데이터입니다. (괄호가 없습니다.)
  - `math.pi`와 같습니다.
  - 따라서 호출하려고 `()`를 사용하지 마세요.
- *멤버 변수(member variable)* 또는 그냥 *멤버(member)*라고 부릅니다.

```{python}
print(data_oceania_country.columns)
```

## 데이터프레임을 전치(transpose)하려면 `DataFrame.T`를 사용하세요.

- 때로는 열을 행으로, 혹은 그 반대로 취급하고 싶을 때가 있습니다.
- 전치(`.T`로 작성)는 데이터를 복사하지 않고 프로그램의 데이터 뷰만 변경합니다.
- `columns`와 마찬가지로 멤버 변수입니다.

```{python}
print(data_oceania_country.T)
```

## 데이터에 대한 요약 통계를 보려면 `DataFrame.describe()`를 사용하세요.

`DataFrame.describe()`는 숫자 데이터가 있는 열의 요약 통계만 가져옵니다.
`include='all'` 인수를 사용하지 않으면 다른 모든 열은 무시됩니다.

```{python}
print(data_oceania_country.describe())
```

- 레코드가 2개뿐일 때는 별로 유용하지 않지만 수천 개가 있을 때는 매우 유용합니다.

:::::::::::::::::::::::::::::::::::::::  challenge

## 다른 데이터 읽기

`gapminder_gdp_americas.csv`의 데이터를 (`gapminder_gdp_oceania.csv`와 같은 디렉토리에 있어야 함)
`data_americas`라는 변수로 읽어 들이고 요약 통계를 표시해 보세요.

:::::::::::::::  solution

## 해답

CSV를 읽어 들이려면 `pd.read_csv`를 사용하고 파일 이름 `'data/gapminder_gdp_americas.csv'`를 전달합니다.
여기서도 `index_col` 매개변수에 열 이름 `'country'`를 전달하여 국가별로 인덱싱합니다.
요약 통계는 `DataFrame.describe()` 메서드를 사용하여 표시할 수 있습니다.

```{python}
data_americas = pd.read_csv('data/gapminder_gdp_americas.csv', index_col='country')
data_americas.describe()
```

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 데이터 검사하기

아메리카 대륙 데이터를 읽어 들인 후 `help(data_americas.head)`와 `help(data_americas.tail)`을 사용하여 `DataFrame.head`와 `DataFrame.tail`이 무엇을 하는지 알아보세요.

1. 이 데이터의 처음 3개 행을 표시하는 메서드 호출은 무엇입니까?
2. 이 데이터의 마지막 3개 열을 표시하는 메서드 호출은 무엇입니까?
  (힌트: 데이터의 뷰를 변경해야 할 수도 있습니다.)

:::::::::::::::  solution

## 해답

1. 데이터프레임의 시작 부분을 볼 수 있게 해주는 `data_americas.head()`를 실행하여 `data_americas`의 처음 5개 행을 확인할 수 있습니다.
  `data_americas.head()`에 대한 호출에서 `n` 매개변수를 지정하여 보고자 하는 행의 수를 지정할 수 있습니다.
  처음 세 행을 보려면 다음을 실행하세요:
  
  ```python
  data_americas.head(n=3)
  ```
  
  ```output
            continent  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
  country
  Argentina  Americas     5911.315053     6856.856212     7133.166023
  Bolivia    Americas     2677.326347     2127.686326     2180.972546
  Brazil     Americas     2108.944355     2487.365989     3336.585802
  
            gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
  country
  Argentina     8052.953021     9443.038526    10079.026740     8997.897412
  Bolivia       2586.886053     2980.331339     3548.097832     3156.510452
  Brazil        3429.864357     4985.711467     6660.118654     7030.835878
  
             gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
  country
  Argentina     9139.671389     9308.418710    10967.281950     8797.640716
  Bolivia       2753.691490     2961.699694     3326.143191     3413.262690
  Brazil        7807.095818     6950.283021     7957.980824     8131.212843
  
             gdpPercap_2007
  country
  Argentina    12779.379640
  Bolivia       3822.137084
  Brazil        9065.800825
  ```

2. `data_americas`의 마지막 세 행을 확인하려면 위에서 사용한 `head()`와 유사한 `americas.tail(n=3)` 명령을 사용합니다.
  하지만 여기서는 마지막 세 열을 보고 싶으므로 뷰를 변경한 후 `tail()`을 사용해야 합니다.
  이렇게 하려면 행과 열이 바뀐 새 데이터프레임을 만듭니다:
  
  ```python
  americas_flipped = data_americas.T
  ```
  
  그런 다음 `americas_flipped`의 마지막 세 행을 보아 `americas`의 마지막 세 열을 볼 수 있습니다:
  
  ```python
  americas_flipped.tail(n=3)
  ```
  
  ```output
  country        Argentina  Bolivia   Brazil   Canada    Chile Colombia  \
  gdpPercap_1997   10967.3  3326.14  7957.98  28954.9  10118.1  6117.36
  gdpPercap_2002   8797.64  3413.26  8131.21    33329  10778.8  5755.26
  gdpPercap_2007   12779.4  3822.14   9065.8  36319.2  13171.6  7006.58
  
  country        Costa Rica     Cuba Dominican Republic  Ecuador    ...     \
  gdpPercap_1997    6677.05  5431.99             3614.1  7429.46    ...
  gdpPercap_2002    7723.45  6340.65            4563.81  5773.04    ...
  gdpPercap_2007    9645.06   8948.1            6025.37  6873.26    ...
  
  country          Mexico Nicaragua   Panama Paraguay     Peru Puerto Rico  \
  gdpPercap_1997   9767.3   2253.02  7113.69   4247.4  5838.35     16999.4
  gdpPercap_2002  10742.4   2474.55  7356.03  3783.67  5909.02     18855.6
  gdpPercap_2007  11977.6   2749.32  9809.19  4172.84  7408.91     19328.7
  
  country        Trinidad and Tobago United States  Uruguay Venezuela
  gdpPercap_1997             8792.57       35767.4  9230.24   10165.5
  gdpPercap_2002             11460.6       39097.1     7727   8605.05
  gdpPercap_2007             18008.5       42951.7  10611.5   11415.8
  ```
  
  이렇게 하면 원하는 데이터가 표시되지만 세 행 대신 세 열을 표시하는 것이 더 나을 수 있으므로 다시 뒤집을 수 있습니다:
  
  ```python
  americas_flipped.tail(n=3).T    
  ```
  
  **참고:** 명령어를 '연결(chaining)'하여 위 작업을 한 줄의 코드로 수행할 수도 있습니다:
  
  ```python
  data_americas.T.tail(n=3).T
  ```

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 다른 디렉토리에 있는 파일 읽기

현재 프로젝트의 데이터는 `field_data` 폴더에 위치한 `microbes.csv`라는 파일에 저장되어 있습니다.
당신은 `thesis`라는 자매(sibling) 폴더에 있는 `analysis.ipynb` 노트북에서 분석을 수행하고 있습니다:


`analysis.ipynb`에서 `microbes.csv`를 읽기 위해 `read_csv`에 어떤 값을 전달해야 합니까?

:::::::::::::::  solution

## 해답

`pd.read_csv` 호출에서 관심 있는 파일의 경로를 지정해야 합니다. 먼저 '../'를 사용하여 `thesis` 폴더에서 빠져나온 다음 'field_data/'를 사용하여 `field_data` 폴더로 이동해야 합니다. 그런 다음 파일 이름 `microbes.csv`를 지정할 수 있습니다.
결과는 다음과 같습니다:

```{python}
data_microbes = pd.read_csv('../field_data/microbes.csv')
```

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 데이터 쓰기

파일에서 데이터를 읽기 위한 `read_csv` 함수 외에도,
Pandas는 데이터프레임을 파일로 쓰기 위한 `to_csv` 함수를 제공합니다.
파일 읽기에 대해 배운 내용을 적용하여
수정된 데이터프레임 중 하나를 `processed.csv`라는 파일에 써보세요.
`help`를 사용하여 `to_csv` 사용 방법에 대한 정보를 얻을 수 있습니다.

:::::::::::::::  solution

## 해답

데이터프레임 `data_americas`를 `processed.csv`라는 파일에 쓰려면 다음 명령을 실행합니다:

```{python}
data_americas.to_csv('processed.csv')
```

`read_csv`나 `to_csv`에 대한 도움말을 보려면 다음 등을 실행해 보세요:

```{python}
help(data_americas.to_csv)
help(pd.read_csv)
```

`help(to_csv)` 또는 `help(pd.to_csv)`는 오류를 발생시킵니다! 이는 `to_csv`가 전역 Pandas 함수가 아니라
데이터프레임의 멤버 함수이기 때문입니다. 즉,
`data_americas.to_csv`나 `data_oceania.to_csv`와 같이 데이터프레임의 인스턴스에 대해서만 호출할 수 있습니다.

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: keypoints

- 표 형태의 데이터에서 기본적인 통계를 구하기 위해 Pandas 라이브러리를 사용하세요.
- `index_col`을 사용하여 특정 열의 값을 행 제목으로 사용하도록 지정할 수 있습니다.
- 데이터프레임에 대해 자세히 알아보려면 `DataFrame.info`를 사용하세요.
- `DataFrame.columns` 변수는 데이터프레임의 열에 대한 정보를 저장합니다.
- 데이터프레임을 전치(transpose)하려면 `DataFrame.T`를 사용하세요.
- 데이터에 대한 요약 통계를 보려면 `DataFrame.describe`를 사용하세요.

::::::::::::::::::::::::::::::::::::::::::::::::::
