---
title: 함수 작성하기 (Writing Functions)
teaching: 10
exercises: 15
---

::::::::::::::::::::::::::::::::::::::: objectives

- 함수를 정의(define)하는 것과 실제로 함수를 호출(call)하여 써먹는 것 사이의 본질적 차이를 분별 설명해 냅니다.
- 딱 정해진 개수의 조그만 입력 인수(arguments)들을 받아들여, 단일 결괏값을 내어놓는 조촐한 함수를 직접 작문해 냅니다.

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: questions

- 내 손으로 나만의 고유 함수(functions)를 직조해 만들어 쓰려면 어찌해야 할까요?

::::::::::::::::::::::::::::::::::::::::::::::::::

## 프로그램 코드가 유순히 읽히고 파악되도록, 거대한 덩어리들을 함수(functions) 단위로 조각조각 쪼개 결속하십시오.

- 무릇 인간의 연약한 두뇌는 한 번에 고작 서너 개의 파편 정보만을 작업 기억 용량(working memory)에 겨우 붙들고 끙끙댈 수 있을 따름입니다.
- 너무 방대하고 복잡 기괴한(larger/more complicated ideas) 작동 원리를 깨달으려면 결국 작게 다듬어진 부품 조각 단위들을 이어 맞추며(combining pieces) 조립 통찰해야 이치에 닿습니다.
  - 마치 거대한 기계 장치 속 수많은 부품(Components) 기어들이 맞물려 도는 것처럼요.
  - 혹은 수학 논증 증명에서 도입하는 여러 보조정리(Lemmas)들 논리처럼요.
- 프로그래밍 세계에서 함수는 딱 저런 본연의 이바지 목적 임무(same purpose) 사명을 위해 존재 발탁됩니다.
  - 코딩의 자잘 구질 통탄할 복잡성(complexity) 난맥상을 깔끔 포장 은닉(*Encapsulate*) 무마시켜 줘서, 하나의 심플한 '행동 장치(single "thing")' 블랙박스처럼 어르고 떡 주무르듯 취급할 수 있게 구제해 줍니다.
- 이뿐만 아니라 그 극성의 알짜배기 재활용(*re-use*) 특권까지 선사 포장해 발부해 주죠.
  - 한 번 공들여 지어 놓고(Write one time), 수십수백 번 뽕을 뽑아 고아 씁니다(use many times).

## 함수 이름을 달아주고 입력칸 매개변수를 둔 뒤 작동 본문 구역을 배정해, `def` 포르테를 냅다 부르짖어 나만의 함수를 규정 선포해 내세요.

- 파이썬 세상에서 새로운 함수 선언 깃발을 내걸려면, 제일 선두에 개시 선언 지시어인 `def` 놈을 꽂아 포문을 열어야 합니다.
- 그 뒤꽁무니에 새로 지어 부여할 여러분의 창작 함수 이름표(name)가 곧장 바짝 견인되어 따라붙죠.
  - 단, 이 작명법 철칙은 일반 변수 이름표 지을 때의 국룰(same rules) 규율 잣대와 아주 매한가지 철저히 똑같이 순응 부합해야 합니다.
- 그러고 나서 곧바로 둥근 괄호 문턱을 쳐, 그 안에다 *매개변수(parameters)* 라 일컫는 입력 접수 빨대들을 꽂아 둡니다.
  - 외부 투입 입력 따위 코웃음 치는 독립 구동 함수라면 그저 텅 빈 괄호표 `()` 만을 달랑 처박아 생략 표식 지으면 그만이죠.
  - 어차피 이 매개변수 구조 심연의 작동 이치 내용은 바로 다음 챕터에서 아주 골이 쪼개지게 파서 논해 볼(discuss this in detail) 참입니다.
- 이 다음 코딱지인 콜론 `:` (콜론) 마개로 기둥 문턱 걸단 종지부를 딱 끊어 짓고 넘어갑니다.
- 그 하부 몸통으로, 전매특허 파이썬 들여쓰기 탭 여백(indented block)을 밀어 박아 들여친 온전한 작업 실행 지령망 체제 코드 본문 블록 세트를 포진 딸려 정렬 배치해 구성해냅니다.

```{python}
def print_greeting():
    print('Hello!')
    print('The weather is nice today.')
    print('Right?')
```

## 함수를 고작 정의해 선언 공표한다고 해서, 그 코드가 저절로 냅다 실행 질주 가동되는 건 절대 아닙니다.

- 백날 천날 함수를 선언 규정(Defining a function)해 놨자 곧바로 스스로 알아서 부르릉 발동 구동 연주되진(not run it) 않습니다.
  - 흡사 이름표 달린 변수에다 고정 수치 값 하나를 처박아 넣고 봉인 배정(assigning a value) 방치해 두듯, 잠자코 호출만을 대기 보류할 따름이죠.
- 그 내부 은닉 결박된 몸통 코드 무더기들을 정말로 출동 격발 실행(execute the code) 구동시켜 불을 지피려면, 기필코 수동 직통으로 그 함수를 명시 호출(call the function) 호명해야지 비로소 발사 가동합니다.

```{python}
print_greeting()
```


## 함수 호출 시 던져 꽂아 넣은 입력 인수(Arguments)들은 어김없이 함수 정의 당시의 접수 매개변수(parameters) 자리에 순서대로 안착 세팅 대응 융합됩니다.

- 함수 뼈대 구조체 기구의 진면목 절대 매력 가치 효용(most useful) 정수는 애초에 제각기 다른 종류별 상이한 낯선 데이터(different data)들에 범용적으로 대거 폭격 범용 호환 대응 투사 조작 처치 가동 연산 가능한 범용 호환 공용 포섭 융합기능 여지 역량에서 꽃핍니다.
- 앞서 함수 원판 뼈대를 제정 규명(defining) 축조 설계할 찰나, 반드시 그 인수 접수 배정 조율을 관장할 징검다리 *매개변수(parameters)* 장교들을 명시 배정(Specify) 해 규정 지어 주십시오.
  - 이 장교 녀석들은 막상 나중 실전 구동 발포 연산 실행(executed) 조작에 돌입할 타이밍 찰나에는 즉석 대리 변수(variables) 녀석들로 돌변 환치 파생 둔갑해 활약 부응합니다.
  - 실 구동 발포 호출 타격 시, 사용자 측에서 던져 꽂아 밀어 넣는 실제 타격 건수 알맹이, 이른바 *인수(arguments)* (즉 함수 뱃속에 투입 전달되는 실물 값어치 결괏값 도출 투입 대상들) 녀석들이야말로 바로 저 매개변수 접수통 구멍에 정확히 할당 배정(assigned) 매칭 투하 장착 도열되는 알맹이들입니다.
  - 여태까지 쭉 호출 사용할 적에, 굳이 던져놓는 타격 알맹이들에다 무슨 딱지 이름표를 호명 지정해 못 박아 매칭 명기 부르지 않았다 치면(don't name the arguments), 그땐 파이썬이 알아서 척척 던진 순서 선착순 배열 도열 차례 순번대로 직렬 기계적 자동 배정 매칭 융합(matched to parameters in the order) 체제로 그냥 척척 일렬 순서 배틀 차례 앞뒤 융합 일렬 착상 체결 도달 규정 밀착 매칭 정률 치환 대조 안착 매칭 도출 배정 결론 배당 조작 정합을 무식히 강행 착안 수행 도달 완수할 요량입니다.

```{python}
def print_date(year, month, day):
    joined = str(year) + '/' + str(month) + '/' + str(day)
    print(joined)

print_date(1871, 3, 19)
```


아니면, 거꾸로 함수 부를 때 투척할 화물 타격 알맹이마다 아예 매칭 타깃 변수 이름표를 아싸리 구체 명시(name the arguments) 호명 못 박아 결박 송출할 수도 있습니다. 이런 방식은 내키는 대로 던질 이름 순번 짬뽕 뒤죽박죽 배열 우회(any order) 허가 무방 투척을 너그러이 용인해주며 코드 가독성 직관 안성맞춤 호출 명료 맵시(clarity) 명시 제고 보완에 극강 혁혁 이점을 부응 부스팅 강화 견인 보탬 공로해줍니다; 까딱 잘못 안일히 순번 투척했다가 훗날 읽는 놈이 "두 번째 알맹이가 이게 달(month) 녀석이었나 날짜(day) 자리였나" 하고 뒷골 잡으며 헷갈려 망각 착각 혼동 패착 여지 수작 망각 파탄 방지 여지 결함 족쇄 혼동 야기 우발 방지 기미 오작동 방지 착오 제지 단절 훼방(forget if the second argument is the month) 차질 분분 무마 결단 타결 배설 모면 회피 방어 공헌 극약 처방 작용에 아주 직효 만점입니다.

```{python}
print_date(month=3, day=19, year=1871)
```


- 저명 트윗 [Twitter](https://twitter.com/minisciencegirl/status/693486088963272705) 비유를 빌리자면 이렇습니다:
  저 둥근 `()` 그릇 통은 단지 요리 함수 가동에 필요한 준비물 요리 재료(ingredients) 식민지 알맹이 집어넣는 접수처일 뿐이고,
  그 매달린 몸통(body) 덩이 안에야말로 비로소 본격 지지고 볶는 진짜배기 조리법(recipe) 타격 절차 강령 메뉴얼이 통째 무장 응집 포진되어 은닉 규명 탑재 묘사 정립 서식한다는 거창 통찰 명언이죠.

## `return` 탈출 수송 반환 포문 문지기 지시어를 투입 설치해, 무사 도출 산출 결과물을 호출자(caller) 품으로 피드백 반환 토해 귀환 선사 건네 반납 무사귀환 거수 전달 헌납 패스 상납 산출 배출 도출 제공 수령 탁송 헌사 증정 토로 투기 적출 산출 선사 귀환 배달할 수단 여지 장치 통로를 뚫어 조작 발현 배설 마련하세요.

- 함수 돌린 최후의 결판 정산 결괏값을 애타게 불렀던 호명 주체 호출자 발원지 본진 쪽으로 고이 실어 도로 답신 환원 토해 무수 토로 귀환 반납(give a value back) 패스 투기 회항 배송 탁달 적출 헌납 도출 적송 전달 인계 배송 하려면 기필코 `return ...` 장치를 발동 동원 투입하세요.
- 이 `return` 관문은 함수 본문 복판 어디 구석구석 시도 때도 없이 꼽사리 등장(anywhere) 난입 불쑥 언제든 출현 잠입 배치 도열 기습 난무 불쑥 무방 끼어들 수습 포진 짱박 무방 가능합니다.
- 거나, 실무 판도 통상 미덕 가독 독자 배려 함수 이해 난독 구강 정립 수월함 통찰 구사 통제 이면(easier to understand) 윤리 정조 잣대 견지 요령 관점 미덕을 쳐 따지자면 가급적 뻔뻔스레 둘 중 한 구석에나 슬쩍 얌전 발발 등재 박아 출몰 등장 출현 짱박 도열 등재 기거 칩거 구경 타결 웅거 구사 빈발 집중 시야 편안 부합 상식 빈도 등장 출석 양태 발생 빈발 작태 시점이 그나마 좀 더 양반 속편 무결 쾌적 속 편안 수월 낫습니다:
  - 초반 도입 최전방 스타트 구역(At the start) 에 특수 예외 불량 사태 돌발 이상 잣대 튕겨 치우는 필터 기점 국면 용도(handle special cases) 수습 차단 방어 수단 조치 배설 차단 단죄 장치 요충용
  - 아니면 전부 다 훑고 돌파 후 홀연 끄트머리 제일 최후미 끝자락 종달 장막(At the very end) 에 장엄한 최종 결괏값 한 뭉텅이 결과 도출(final result) 산출 성과 수확물을 떡하니 고이 안착 배설 수거 취합 결집 도출 배송 동봉 토로 전달 완수 귀환 보송 송부 발신 대미 탁달 송출 목적 귀결 용도로 말이죠.

```{python}
def average(values):
    if len(values) == 0:
        return None
    return sum(values) / len(values)
```

```{python}
a = average([1, 3, 4])
print('실제 입력 값들의 평균치:', a)
```


```{python}
print('텅 빈 빈깡통 리스트의 평균치 결과:', average([]))
```


- 늘 항시 명심 망각 염두 주의 기조 법칙 하나 철칙 망각 절대 명심(Remember): [파이썬 세상의 모든 구동 함수는 필경 무조건 뭐라도 하나 결괏값을 무사 뱉어내 토해 귀환 반납 배출 도출 거수 산출(every function returns something) 배정 적출 패스 헌사 결론 반납 도출합니다](04-built-in.md).
- 여러분이 귀찮아서 저 `return` 반환 탈주 포문 명시 지시어를 굳이 대놓고 대놓고 코드 줄에 안 박아 넣은 무성의(doesn't explicitly `return`) 허당 깡통 함수라 칠지언정, 파이썬 뒤통수 뒷골목 무대 뒤에선 이 악물고 알아서 빈 껍데기 기호 `None` (없음 기호) 고철 마개라도 기어코 결괏값으로 둔갑 억지 치환 강제 둔갑 자동 발급 토로 반환 투기(automatically returns `None`) 무마 땜빵 땜질 무마 대미 방출 체결 제공 땜질 타결 종결 땜빵 정산 마무리를 지어 패스 던져 거수 배정해 주고야 마는 악바리 습관 생리 귀걸 본능 기조 결말 기조 습성 태생 이치를 단단히 명심 지침 간파 염두 주지 각인 착안 명심 직시 통탄 숙지하세요.

```{python}
result = print_date(1871, 3, 19)
print('함수 호출의 반환 결괏값의 정체는:', result)
```


:::::::::::::::::::::::::::::::::::::::  challenge

## 구문 오류(Syntax Errors) 직시 판별 통찰하기

1. 직접 파이썬 구동 커맨드를 먼저 때려보기 *전에*, 오직 순수 텍스트 눈요기(read the code below) 육안 관찰 판독만으로 이 하단 코드의 어느 구석탱이가 썩어 문드러졌는지 오류 정체(identify what the errors are)를 가늠 짐작해 내 예측 탐색해 보세요.
2. 이제 비로소 코드를 생으로 실행 구동해 보고 파이썬 엔진이 토해낸 뻘건 에러 메시지(error message) 원문을 정독 직시해 봅니다.
  이게 보아하니 문법 규격을 위반한 `SyntaxError` 부류 사단인가요, 아니면 줄 맞춤 공백 탭 여백 불량인 `IndentationError` 파탄인가요?
3. 발견한 그 오류 파탄을 말끔 공사 정비 고쳐내 수리(Fix the error) 복구하세요.
4. 더 이상 그 어떤 뻘건 에러 메시지도 구토 출몰 발동 산출되지 않을 지경까지 무한 반복 2번과 3번 과정을 순환 복기 이행 타개 종결 해결(Repeat) 달성해 내세요.

```{python}
def another_function
  print("Syntax errors are annoying.")
   print("But at least python tells us about them!")
  print("So they are usually not too hard to fix.")
```

:::::::::::::::  solution

## 해답

```{python}
def another_function():
  print("Syntax errors are annoying.")
  print("But at least Python tells us about them!")
  print("So they are usually not too hard to fix.")
```

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 함수 정의와 호출 이행 (Definition and Use)

과연 이 다음 프로그램 스크립트 코드의 맨 마지막 최종 출력 결과물(print) 정체는 무엇이 될까요?

```{python}
def report(pressure):
    print('pressure is', pressure)

print('calling', report, 22.5)
```

:::::::::::::::  solution

## 해답


파이썬에서 어떤 함수 녀석을 정식 호출 발동 격발(call)하려면 무조건 필히 뒤통수에 저 둥근 괄호표 `()`(parenthesis)가 껌딱지처럼 들러붙어 따라와 줘야만 합니다. 만약 저걸 쏙 빼먹고 냅다 그냥 생이름줄만 던져 부른다면, 파이썬은 저걸 함수 호출 명령이 아니라 그냥 함수라는 존재 그 자체의 거주지 메모리 주소값(memory address of the function object) 딱지를 뱉어 적출 반환해 버리는 딴청을 피웁니다. 고로, 우리가 지금 진짜 원했던 저 `report` 함수를 구동시켜 22.5라는 실물 데이터를 던져 보고용 타격 처리하게 시킬 본래 목적 의향이었다면, 함수 호출 격발문 꼬락서니를 필히 다음과 같이 재정비 보수해 작성 투여(function call as follows) 호출 격발했어야 타당 합당 궤도 기조에 맞습니다.

```{python}
print("calling")
report(22.5)
```


::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 선입선출 실행 가동 순열 우선순위 (Order of Operations)

1. 아래 제시된 엉터리 예제 코드 블록의 어느 국면 뭐가 잘못 배알 꼬였는지(What's wrong) 진단 규명해 보시죠?
  
  ```python
  result = print_time(11, 37, 59)
  
  def print_time(hour, minute, second):
     time_string = str(hour) + ':' + str(minute) + ':' + str(second)
     print(time_string)
  ```

2. 위에서 지적한 그 앞뒤 모순 착오 오류 문제점을 수리 보수한 다음, 자 이제 왜 하단 코드의 수정 예제를 생으로 돌렸을 때:
  
  ```python
  result = print_time(11, 37, 59)
  print('함수 호출의 반환 결괏값의 정체는:', result)
  ```
  
  이런 황당한 출력 내용물(output) 결괏값만 토해 뱉어내는지 조목조목 이유를 설파 해명(explain why) 진단해 내 보세요:
  
  ```output
  11:37:59
  함수 호출의 반환 결괏값의 정체는: None
  ```

3. 어찌하여 필경 최종 반환(result of the call) 도출 수령 결괏값이 저 허무한 `None` 빈 깡통으로 발현 도달 타결 결론 나버렸을까요?

:::::::::::::::  solution

## 해답

1. 저 상기 코드 예제의 치명적 문제 결함은 바로 함수 개국 선포 규정 선언 선언문(`print_time()` is defined) 진영이 정작 그 함수를 불러재끼는 뻔뻔한 호출 지시문(*after* the call) 타격 발포 라인보다 뒤늦게 맨 아래 후방 거꾸로 밑바닥 층에 뒤치다꺼리로 후미에 자리하고 있다는 서열 배탈 파탄 점입니다. 파이썬 엔진은 워낙 융통성 없는 윗선 낙하 일직선 독재 체제라 자기가 지금 밟고 있는 위쪽 라인 지경까지 아직 저 `print_time` 이란 놈의 명칭 이름 석 자 존재 자체를 듣도 보도 선언받지도 못한 인지조차 못한(hasn't been defined yet) 노릇이거늘 다짜고짜 당장 뛰어나와 일하라 호명하니 당연히 그딴 놈 모른다며 생으로 `NameError` 발작 오류를 거품 물고 토해낼 수밖에요 (e.g.,
  `NameError: name 'print_time' is not defined`).

2. 출력 화면 첫 줄의 저 시간 형식 `11:37:59` 문구 녀석은 첫 번째 지시문 `result = print_time(11, 37, 59)` 저 라인 속의 `print_time` 함수가 직접 자기 수명 본문 안에서 터트린 수행 동작 여파로 찍혀 나온 프린트 발자취입니다. 그리고 연이어 곧장 출력된 저 두 번째 구문 라인은 맨 밑 저 두 번째 부가 `print` 인쇄소 지시문, 즉 `result` 변수 그릇에 담긴 본래 알맹이 꼴을 냅다까라 찍어 열람해 보여주라(print the contents) 강타 지시한 적출 후반 타격 발동 연여파 산출 파장 결과 출력물입니다.

3. 애당초 우리 `print_time()` 함수 뱃속 본문 내장 코드를 까보면, 자기 스스로 능동적 결괏값을 바깥세상으로 도로 토출 수송 포문 해 적출해 주마 반환 발송 지시를 내리는 저 `return` 문지방 탈출문 배설 장치 구문이 단 한 점도 구비 안 된 나태 부재 불량 기조(does not explicitly `return` a value) 부재 은닉 사태 형국입니다. 그리되니 파이썬 규율 이치 생리 절대원칙상 그냥 알아서 어쩔 수 없이 묻지 마 땜빵 결론치인 깡통 `None` (없음 고철 값)만을 최종 도출 투기 반납 적출 반환(automatically returns `None`) 무마 수거 조치해 대미를 얼버무려 타결 종결 성립 끝장내버린 셈입니다.

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 기능 압축 포장 결박 은닉화 (Encapsulation)

아래 여백 빈칸 장막을 채워 완성 조립해 내, 딱 단 하나의 파일 명칭(single filename) 문자열만을 덜렁 인수로 주입받아
해당 지목된 그 파일의 뱃속 내용물 데이터를 꿀꺽 적출 로드 집어삼킨 뒤(loads the data),
그 내부 데이터 스펙 덩어리 전역에서 제일 자질구레 쪼잔한 가장 꼴지 최저 밑바닥 최솟값(minimum value) 수치를 끄집어내 
도로 최종 결괏값으로 토출 산출 탈출 반환 거수해 던져주는(returns) 야무진 원큐 단일 함수를 고안 완성 기구(create a function) 직조 창조 건립해 구축해 보시죠.

```{python}
import pandas as pd

def min_in_data(____):
    data = ____
    return ____
```

:::::::::::::::  solution

## 해답

```{python}
import pandas as pd

def min_in_data(filename):
    data = pd.read_csv(filename)
    return data.min()
```

:::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 첫빠따 색출 탐지하기 (Find the First)

하단 빵꾸 뚫린 빈칸 막을 적절히 타개 수복하여, 오지게 늘어선 숫자 리스트 한 다발을 통째 인수로 받아먹은 뒤
그중 맨 처음 눈에 띄는 불량배, 즉 첫 번째 음수(negative) 마이너스 수치값을 도로 적출 반환해 건네주는 탐지기 함수를 제조 생성해 내십쇼.
만약 누군가 애초부터 텅텅 빈 깡통 리스트를 냅다 던져 입력하면 이 함수는 과연 어떤 꼬락서니 변모 결과행 작동을 발동해 토해낼까요? 
마이너스 음수가 단 한 마리도 없는 아주 건전 다이아몬드 청정 양수 리스트라면 또 어떤 꼴이 날까요?

```{python}
def first_negative(values):
    for v in ____:
        if ____:
            return ____
```

:::::::::::::::  solution

## 해답

```{python}
def first_negative(values):
    for v in values:
        if v < 0:
            return v
```

만일 텅 빈 깡통 공백 리스트라든가 전부 100% 양수치로만 도배된 청정무결 리스트를 이 녀석에게 던져 주입하면, 애초에 저 내부 루프문 산하 `return` 탈출선 관문을 단 한 번도 진입 못 하고 그대로 맹탕 통과(skip)해 버리게 됩니다. 고로 끝끝내 반환치 발급을 달성 못한 함수 생리 이치상 결국 기계적 허무 땜빵 표식인 `None` 을 적출 토해내게 됩니다:

```{python}
my_list = []
print(first_negative(my_list))
```


::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 함수 호출 시 명찰 달아 호출하기 (Calling by Name)

아까 전 위쪽 코너에서 우린 이 하단 함수를 접해본 바 있습니다:

```{python}
def print_date(year, month, day):
    joined = str(year) + '/' + str(month) + '/' + str(day)
    print(joined)
```

그리고 이 함수를 써먹을 적 구동 찰나에 *명명된 인수(named arguments)* 지명 딱지 구문을 써서 대놓고 아래처럼 호명 통신 주입할 수 있다는 비기도 살펴봤죠:

```{python}
print_date(day=1, month=2, year=2003)
```

1. 그래 저 `print_date(day=1, month=2, year=2003)` 호출 타격 결과물로 실상 프린트 인쇄 산출되는 종착 글귀는 뭡니까?
2. 여태 파이썬 기초 순례를 벌이면서, 어디선가 과연 저런 꼬락서니의 지명 딱지 기반 함수 호출(function call like this) 문법을 눈요기로 접해본 적이 있던가요?
3. 과연 도대체 어느 국면 찰나 시점 어떤 뇌피셜 이점이 있기에 굳이 이딴 식으로 길고 거추장스럽게 이름표 구문을 못 박아 달배정 호칭 작용 호출 방식을 구사 타당 실무 기용하는 걸까요?

:::::::::::::::  solution

## 해답

1. `2003/2/1`
2. 우린 진즉 과거 pandas 판다스 괴물 라이브러리의 신기를 맛보며 그 작동 현장 한복판에서 저 *명명된 인수(named arguments)* 구사 방식 단물을 숱하게 투여 접해본 전적이 있습니다. 예컨대 `data = pd.read_csv('data/gapminder_gdp_europe.csv', index_col='country')` 라고 데이터 집결 세트를 욱여넣고 로드 호출 적재할 때, 맨 뒤에 매달린 `index_col` 이란 녀석이 바로 저 지명 확정 명찰 딱지 인수 문법 기조입니다.
3. 굳이 저렇게 꼬박꼬박 *명명된 인수* 기조를 고집 부려먹으면, 제3자 독자 인간이 호출 구문 코드 문짝만 쓱 쳐다봐도 "아하 이 구멍 안에는 이런저런 속성 데이터놈들이 주입되어 들어가는구나" 하고 즉석 직관적 판독 간파가 쏠쏠히 트이게 돼 코드 가독성(코드 해독 읽기 편의성, code more readable)이 끝내주게 제고 보완 탁달 진전됩니다. 
  뿐만 아니라 인수를 무심코 실수 연발 앞뒤 순서 막무가내 짬뽕 뒤바꿔 던져 넣다가 오류 수렁을 야기 초래할 재앙 파탄 불상사 맹점 착오(chances of passing arguments in the wrong order) 빈도를 대거 차단 방비 박살 내 줍니다; 명칭 딱지만 박혀 있다면 그 던지는 차례 짬짜면 순서 지진(order doesn't matter) 따위야 안중 패스 무방 무관 안심 무조건 찰떡 융합 안착할 수 있으니까요.
  
  

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 단일 if 판독 블록 코드의 함수 포장 은닉화 (Encapsulation of an If/Print Block)

아래 하단에 포진한 코드는 훗날 닭알(계란) 분류용 라벨 프린터 기계에 탑재돼 굴러갈 작동 구문입니다. 디지털 저울이 방금 측정한 계란의 실제 중량(그램 단위)을 컴퓨터 엔진에 통보해오면, 컴퓨터 본체가 알맞은 등급 라벨을 프린터로 찍어내는 원리죠.

```{python}
import random
for i in range(10):

    # simulating the mass of a chicken egg
    # the (random) mass will be 70 +/- 20 grams
    mass = 70 + 20.0 * (2.0 * random.random() - 1.0)

    print(mass)

    # egg sizing machinery prints a label
    if mass >= 85:
        print("jumbo")
    elif mass >= 70:
        print("large")
    elif mass < 70 and mass >= 55:
        print("medium")
    else:
        print("small")
```

계란 등급을 판독 단죄하는 저 `if` 블록 로직(classifies the eggs)은 나중에 다른 딴 동네 프로그램이나 구역 상황에서도 쏠쏠하게 우려먹을 여지 구석이 다분합니다. 저런 노가다를 다시 구구절절 반복 타이핑하는(avoid repeating it) 처참한 사태를 모면 방지하고자 아예 저놈을 똑 떼어내 `get_egg_label()` 이란 통솔 함수 껍데기 복판 안에다 고스란히 이식 안착 포장해 은닉 무마시켜 버립시다(fold it into a function).
그리하여 이 새로 만든 원큐 함수를 불러내어 과거 기존 구문을 전면 개편(Revising the program) 개조해 본다면 대강 이런 신박한 자태가 나올 터입니다:

```{python}
# revised version
import random
for i in range(10):

    # simulating the mass of a chicken egg
    # the (random) mass will be 70 +/- 20 grams
    mass = 70 + 20.0 * (2.0 * random.random() - 1.0)

    print(mass, get_egg_label(mass))

```

1. 위에서 투척 제시된 저 영롱한 개편 선진화 버전 프로그램과 찰떡 궁합으로 제대로 호환 굴러갈 수 있게끔, 저 `get_egg_label()` 녀석의 실물 함수 정의(definition) 몸통 블록을 직접 코딩 타이핑해 구축해 보세요. 이때 이 `get_egg_label()` 함수가 토해낼 반환 결괏값(`return` value)의 존치 유무 및 그 정체 역할이 매우 중차대하다는 점을 명심 각인하세요. 위 개조 프로그램이 정상 무사 통과 수복 작동했을 시 얻게 될 모범 찰떡 출력 결과물(Sample output)의 한 줄 외관 맵시는 필시 `71.23 large` 이런 식의 우아한 자태일 겝니다.
2. 만일 진흙투성이 오염된 뚱뚱한 계란이라면 무게가 자그마치 90그램을 훌쩍 능가 돌파할 공산이 크며, 아마 썩거나 바스러져 노른자가 샌 불량 파손 계란 따위는 중량이 50그램 미만으로 초라할 게 유력 농후합니다. 여러분의 저 `get_egg_label()` 함수 내부 로직을 뜯어고쳐, 이런 돌발 예외 막장 에러 징후 상황(error conditions)조차 무사안일 판독 분류 단죄 타개 포용 통제가 가능하게껏 심판 조건을 확장 증설 보완 개수해내십시오. 이 패치 업그레이드 수라장을 통과한 신삥 모범 기조 출력 결과물(Sample output)의 한 위엄은 장담컨대 `25 too light, probably spoiled` 이런 폼새 문구일 테죠.

:::::::::::::::  solution

## Solution

```{python}
def get_egg_label(mass):
    # egg sizing machinery prints a label
    egg_label = "Unlabelled"
    if mass >= 90:
        egg_label = "warning: egg might be dirty"
    elif mass >= 85:
        egg_label = "jumbo"
    elif mass >= 70:
        egg_label = "large"
    elif mass < 70 and mass >= 55:
        egg_label = "medium"
    elif mass < 50:
        egg_label = "too light, probably spoiled"
    else:
        egg_label = "small"
    return egg_label
```

:::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 데이터 조작 뻘짓 로직의 함수 은닉 포장 캡슐화 (Encapsulating Data Analysis)

아래 하단 코드가 이미 진즉에 무사 구동 돌파 완료됐다고 가정해 봅시다:

```{python}
import pandas as pd

data_asia = pd.read_csv('data/gapminder_gdp_asia.csv', index_col=0)
japan = data_asia.loc['Japan']
```

1. 구멍 뚫린 하단 코드 문맥을 마저 완수 채워 넣어, 보고된 1980년대 아시아 데이터 중
  일본(Japan) 영토의 해당 10년 연평균 1인당 GDP 도합 통계치(average GDP for Japan)를 산출해 내십시오.
  
  ```python
  year = 1983
  gdp_decade = 'gdpPercap_' + str(year // ____)
  avg = (japan.loc[gdp_decade + ___] + japan.loc[gdp_decade + ___]) / 2
  ```

2. 성공했다면, 방금 조립해 낸 저 위 날것의 연산 코드를 통으로 단일 함수 내부로 추상화 편입 구축해 보세요(Abstract the code above).
  
  ```python
  def avg_gdp_in_decade(country, continent, year):
      data_countries = pd.read_csv('data/gapminder_gdp_'+___+'.csv',delimiter=',',index_col=0)
      ____
      ____
      ____
      return avg
  ```

3. 만일 우리가 사전에 "이 데이터의 각 연도 칼럼은 특정 끝자리 숫자 몇몇 연도만 불규칙하게 쏙쏙 빠져 적혀 있더라" 하는
  어떤 예지 정보도 없는 캄캄 까막눈(did not know beforehand which specific years) 상태라면 어찌해야 저 함수를 만능으로 굴러가게 일반화(generalize) 융통성 개조할 수 있을까요?
  이를테면, 앞으로 던져질 데이터가 10년대별로 달랑 끝자리가 '1'년도랑 '9'년도인 놈들만 모조리 뭉뚱그려져 적재돼 있을 수도 있잖아요?
  (힌트: 쓸데없이 코드상에 연도를 하드코딩 일일이 나열해 박아넣지 말고(instead of enumerating them), `columns` 속성을 발라내 뒤적여서 해당 10년대에 딱 들어맞는 놈들만 자체 필터링해 솎아 긁어오도록 짜보십시오.)

:::::::::::::::  solution

## 해답

1. 1980년대 전역 보고 연수 기준, 일본 땅의 1인당 GDP 평균치는 다음 수식 전개로 돌출 적출됩니다:
  
  ```python
  year = 1983
  gdp_decade = 'gdpPercap_' + str(year // 10)
  avg = (japan.loc[gdp_decade + '2'] + japan.loc[gdp_decade + '7']) / 2
  ```

2. 그걸 뚝딱 함수로 포장 봉인한 전모는 이렇습니다:
  
  ```python
  def avg_gdp_in_decade(country, continent, year):
      data_countries = pd.read_csv('data/gapminder_gdp_' + continent + '.csv', index_col=0)
      c = data_countries.loc[country]
      gdp_decade = 'gdpPercap_' + str(year // 10)
      avg = (c.loc[gdp_decade + '2'] + c.loc[gdp_decade + '7'])/2
      return avg
  ```

3. 어떤 숫자의 연도가 들어차 있는지 모를 때 평균을 내려면, 결국 칼럼 이름표 뭉치들(relevant years)을 모조리 뺑뺑이 순회 순환 검색해 봐야 합니다:
  
  ```python
  def avg_gdp_in_decade(country, continent, year):
      data_countries = pd.read_csv('data/gapminder_gdp_' + continent + '.csv', index_col=0)
      c = data_countries.loc[country]
      gdp_decade = 'gdpPercap_' + str(year // 10)
      total = 0.0
      num_years = 0
      for yr_header in c.index: # 이 c 객체의 index 배 부위엔 보고된 연도명 컬럼 딱지들이 쫙 깔렸습니다
          if yr_header.startswith(gdp_decade):
              total = total + c.loc[yr_header]
              num_years = num_years + 1
      return total/num_years
  ```

이제 이렇게 일신 진보한 함수는 손쉽게 한 줄 문구로 호명 발포할 수 있죠:

```{python}
avg_gdp_in_decade('Japan','asia',1983)
```


::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## 동적인 요동계 시스템 모의 전개 구동 (Simulating a dynamical system)

수학 이치 세상에서 [동역학계(dynamical system)](https://en.wikipedia.org/wiki/Dynamical_system) 란 곧 어떤 공간 속 국면 지표가 
시간차 기조의 흐름 양상 파동에 따라 어찌 등락하며 돌발 변화하는지를 함수식으로 통계 모사 기술 규명하는 체계를 일컫는 용어입니다.
이 요동 시스템의 최고 간판 단골 대표 주자 모범 사례가 바로 [로지스틱 사상(logistic map)](https://en.wikipedia.org/wiki/Logistic_map) 이란 성장 곡선 모방식인데,
지금 현재의 인구 밀집도 수치를 기조로 바탕 삼아 통계망을 굴러 바로 다음 턴의 인구 번식 밀도(0에서 1 사이의 비율값)를 예측 투사 산출해내는 방정식이죠.
이 모델계 공간에선 무자비한 분침이 아닌 오직 0, 1, 2... 식의 똑깍이는 정수 불연속 턴(discrete values) 개념으로만 시간(`t`)이 흐릅니다.

1. 먼저 `logistic_map` 이라는 당찬 이름 석 자를 하사해 함수 하나를 정의 축하 건립하십시오. 이놈은 무조건 두 개의 입력 인수(inputs)를 받아먹습니다: 현재 `t` 시점의 인구 상태 밀도비인 `x`, 
  그리고 잣대 조율 통제 파라미터인 `r` (이 녀석은 `r = 1` 로 초기 설정).
  이제 이 함수 심연에선 다음 턴 시간(`t + 1`) 시점에 당도할 요동 시스템상 다음 기수 인구 밀도 결갏값을 연산 추정해 토출 반환(return a value)해 주어야 하는데, 그 척추 공식 뼈대는 다음 사상 변환 수식과 일치합니다:
  
  `f(t+1) = r * f(t) * [1 - f(t)]`

2. 그 다음 파면, `for` 루프건 `while` 뺑뺑이 루프건 암거나 하나 물고 와서, 앞서 만들었던 `logistic_map` 함수 포신에다 
  맨 처음 태초 초기화 인구수(`initial population`) 0.5비 수치를 투척 밀어 넣어 스타트를 끊으십쇼. 
  그러고 장장 전체 기간 기수 `t_final = 10` 동안 뺑뺑이 포문을 퍼부어 거듭 재귀 순환 발동시키십쇼. 
  턴마저 얻어낸 중간 파생 추정 도출 결갏값(intermediate results)들은 전부 리스트 바구니 한 켠에 차곡차곡 축적 모아 싸 짊어져 두세요.
  루프 탈출이 강제될 무렵 당신 손엔 총 `t = [0,1,...,t_final]` 기점에 걸친 (총 11개의 덩어리로 점철된) 인구 변동 궤적 리스트 일대기 시퀀스가 손수 적립 체결 포획 완수돼 들려 있어야 합니다.
  이 결과 수집 리스트를 모니터 화면에 대놓고 산출 찍어서(`Print`), 참새만 한 인구가 어떻게 개미 치명 부침 전락하는지 일련의 역사를 관측 감상 통찰해 봅시다.

3. 방금 빙글빙글 노가다 돌리던 그 거추장루프 뺑뺑이(logic of your loop) 장치를 아예 통째로 뜯어 발라 `iterate` 라는 통치 함수 안에 구겨 넣어 은닉 투하 병합(Encapsulate)해 내십시오.
  이 대통합 함수는 세 가지 재료를 갈취 받아먹을 겁니다: 첫째 인수로 태초 초기 밀도(`initial population`), 두 번째 인수로 장전할 타임 턴 기수(`t_final`), 셋째 인수로 잣대 상수 `r`.
  당연히 얘를 찔러 구동 호명하면, 아까처럼 저 `t = [0,1,...,t_final]` 변천사 시대의 도합 밀도 역사가 담긴 통 리스트가 결갏값으로 빠져나와 패스 귀환 건네져야 정상입니다.
  이제 본격 체제 완비된 이 통치 함수를 향해 포문을 맞춰, 호쾌하게 `t_final = 100` 수치랑 `1000` 치 턴 장전을 먹여 무대포 돌려보시고
  그 후반 막바지 몇몇 턴 대 결과 부분값들을 인쇄 산출 비교 점검해 보시죠. 
  무턱대고 난동만 부릴 줄 알았던 인구 숫자가 점점 특정 한계점 언저리로 귀소 접근 수렴 평행(trending toward a steady state) 안정화 기조를 보이진 않았습니까?

:::::::::::::::  solution

## 해답

1.
  ```python
  def logistic_map(x, r):
      return r * x * (1 - x)
  ```

2.
  ```python
  initial_population = 0.5
  t_final = 10
  r = 1.0
  population = [initial_population]

  for t in range(t_final):
      population.append( logistic_map(population[t], r) )
  ```

3.
  ```python
  def iterate(initial_population, t_final, r):
      population = [initial_population]
      for t in range(t_final):
          population.append( logistic_map(population[t], r) )
      return population
  
  for period in (10, 100, 1000):
      population = iterate(0.5, period, 1)
      print(population[-1])
  ```

  ```output
  0.06945089389714401
  0.009395779870614648
  0.0009913908614406382
  ```
  
  저 무자비한 숫자의 추락 변동세를 구경 보아하니 인구 밀도가 점차 바닥 제로 멸종 0점(approaching zero)을 향해 곤두박질치는 양상이 연출됩니다.
  
  

::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::::  callout

## Pandas 조건절 판단 구문과 함수 융합 사용법 (Using Functions With Conditionals in Pandas)

다수 함수들의 뱃속에는 조건절 논리가 내장되어 있기 마련입니다. 하단에 나열된 짧은 예제 함수는
직접 일일이 핀셋으로 입력 못 박은 기준점(cut points) 체계 사분위수(quartile)에 입각하여 
현재 들어온 데이터 인수가 전체 1~4 구역 중 어느 구간 사분위에 안착해 있는지 식별 가늠해 냅니다.

```{python}
def calculate_life_quartile(exp):
    if exp < 58.41:
        # 이 관측치 녀석은 1사분위에 안착하셨습니다
        return 1
    elif exp >= 58.41 and exp < 67.05:
        # 이 관측치 녀석은 2사분위에 소속 배정 완료
       return 2
    elif exp >= 67.05 and exp < 71.70:
        # 이 관측치 녀석은 3사분위 안착 명단에 오름
       return 3
    elif exp >= 71.70:
        # 이 관측치 녀석은 최종 최정상 4사분위에 등극
       return 4
    else:
        # 이 관측치는 어딘가 비뚤어진 에러 불량(bad data) 데이터
       return None

calculate_life_quartile(62.5)
```


통상 이런 분류 판독 함수 녀석들은 거친 `for` 루프 뺑뺑이 한가운데서 도구로 불려 다니기 일쑤입니다만, Pandas는 
동일한 저 조작판을 아주 효율 극대화 노선으로 단방에 후려치는 신묘한 우회 수법, 일명 데이터프레임 전역 혹은 부분 파벌에 
딱 함수 하나를 *일괄 적용 지시 투하(applying)* 타격하는 융합 무기를 구비하고 있습니다. 
아까 만든 저 위 방침 함수를 도구 삼아 그 진면목 예제를 바로 출격 살펴봅시다.

```{python}
data = pd.read_csv('data/gapminder_all.csv')
data['life_qrtl'] = data['lifeExp_1952'].apply(calculate_life_quartile)
```

저 두 번째 줄에는 엄청 많은 의미 기교 짬짜면이 함축 내포돼 있으니 한 꺼풀씩 뜯어 해부해 보겠습니다.
먼저 `=` 대입 기호 우측에 포진한 `data['lifeExp_1952']` 장군은 `data` 란 라벨이 붙은 데이터프레임 부대 안에서 명찰 딱지 `lifeExp_1952` 을 단 직속 칼럼 병력들만을 특정 차출해 낸 집단입니다. 
그 집단에다 냅다 바로 `apply()` 마법 타격을 걸면 문자 그대로 행동 발사됩니다: 그 특정 컬럼줄 소속 매 하나의 독립 행(row) 칸칸마다 
그 속의 값어치를 뽑아다 예의 저 `calculate_life_quartile` 판독 함수 구멍에 순서대로 욱여넣어 돌리고 최종 심판 결괏값만 도로 배출 도출 반환해다 주는 위엄을 자랑합니다.


::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: keypoints

- 덩치 크고 골치 아플 모듈식 프로그램 코드는 함수(functions) 덩어리로 조각조각 잘게 추상화 쪼개 분해해야 제3자도 유순히 알아먹고 파악할 수 있게 유도됩니다.
- 함수 시작 지점엔 포르테 `def` 를 박고 뒤이어 함수 명찰, 둥근 괄호 매개변수 통로, 그리고 블록화된 코드 본문을 순차 융합 배정해 정의 선언합니다.
- 함수를 정의 공표(Defining) 규정했다고 해서 냅다 곧장 프로그램이 그걸 실행 격발해주진(not run it) 않습니다.
- 함수 호출 찰나에 욱여넣은 투척용 인수(Arguments) 대원들은 고스란히 정의 선포 당시 규정 배정해 놓은 접수 매개변수(parameters) 구멍에 순번대로 척척 안착 매칭 융합 대응 서식하게 됩니다.
- 함수 뱃속의 온갖 우여곡절 고군분투 끝에 도출된 결판 결괏값(result)은 필경 탈출 포문 장치인 `return` 을 거쳐 자신을 출동 호명했던 호출자(caller) 복귀 지점 사령부로 고이 반환 토출 적송 탁달 조치 귀환됩니다.

::::::::::::::::::::::::::::::::::::::::::::::::::


